import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Agent } from "@cursor/sdk";

import type { IDashboardPlan, IInstrumentReport, IProgressReporter } from "./types.js";
import { dashboardPlanSchema } from "./types.js";

export interface IDashboardAgentOptions {
  dryRun: boolean;
  reporter: IProgressReporter;
}

const PROMPT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "prompts",
  "dashboardAgent.md",
);

const toTitleCase = (eventName: string): string => {
  return eventName
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
};

const isFunnelCandidate = (events: string[]): boolean => {
  const viewedEvents = events.filter((event) => event.endsWith("_viewed"));

  return viewedEvents.length >= 2;
};

export const buildDashboardPlanDeterministic = (
  report: IInstrumentReport,
): IDashboardPlan => {
  const allEvents = report.newEvents;
  const decisions = [
    {
      summary: "Deterministic dashboard planning",
      reason:
        "Generated without AI using new events from the instrumentation report.",
    },
  ];
  const reports: IDashboardPlan["reports"] = [];

  for (const eventName of allEvents) {
    if (eventName.endsWith("_viewed")) {
      reports.push({
        type: "insights",
        name: `${toTitleCase(eventName)} Trend`,
        description: `Daily trend for ${eventName}`,
        event: eventName,
        reason: `New page view event ${eventName} added in this PR`,
      });
    }
  }

  const actionEvents = allEvents.filter(
    (event) => !event.endsWith("_viewed") && event.includes("_"),
  );

  for (const eventName of actionEvents) {
    reports.push({
      type: "insights",
      name: `${toTitleCase(eventName)} Trend`,
      description: `Daily trend for ${eventName}`,
      event: eventName,
      reason: `New user action event ${eventName} added in this PR`,
    });
  }

  if (isFunnelCandidate(allEvents)) {
    const viewed = allEvents.filter((event) => event.endsWith("_viewed"));

    if (viewed.length >= 2) {
      reports.push({
        type: "funnels",
        name: "Checkout Retry Funnel",
        description: "Conversion across newly instrumented checkout retry flow",
        steps: viewed.slice(0, 3),
        reason: "Multiple page view events suggest a multi-step funnel",
      });
    }
  }

  if (reports.length === 0) {
    reports.push({
      type: "insights",
      name: "Instrumented Events Overview",
      description: "Fallback insights report for instrumented events",
      event: allEvents[0] ?? "page_viewed",
      reason: "No event-specific plans matched; using fallback report",
    });
  }

  return dashboardPlanSchema.parse({
    decisions,
    reports,
  });
};

const loadPrompt = (): string => readFileSync(PROMPT_PATH, "utf8");

const extractDashboardPlan = (text: string): IDashboardPlan | null => {
  const jsonMatch = text.match(/\{[\s\S]*"reports"\s*:\s*\[[\s\S]*\]\s*\}/);

  if (!jsonMatch) {
    return null;
  }

  try {
    const parsed = JSON.parse(jsonMatch[0]) as unknown;

    return dashboardPlanSchema.parse(parsed);
  } catch {
    return null;
  }
};

export const runDashboardAgent = async (
  report: IInstrumentReport,
  options: IDashboardAgentOptions,
): Promise<IDashboardPlan> => {
  const { dryRun, reporter } = options;

  reporter.phaseStart("dashboard-agent");

  if (dryRun || !process.env.CURSOR_API_KEY) {
    const reason = dryRun ? "dry-run mode" : "CURSOR_API_KEY not set";
    reporter.decision(
      "dashboard-agent",
      "Deterministic fallback",
      `Using rule-based planner (${reason})`,
    );
    const plan = buildDashboardPlanDeterministic(report);
    reporter.setDashboardPlan(plan);
    reporter.phaseComplete("dashboard-agent", "complete");

    return plan;
  }

  const prompt = `${loadPrompt()}\n\n## Instrumentation report\n\n${JSON.stringify(report, null, 2)}\n\nReturn only valid JSON matching the dashboard plan schema.`;

  try {
    const result = await Agent.prompt(prompt, {
      apiKey: process.env.CURSOR_API_KEY,
      model: { id: "composer-2.5" },
      cloud: {},
    });

    const parsed = result.result ? extractDashboardPlan(result.result) : null;

    if (parsed) {
      reporter.decision("dashboard-agent", "AI plan", "Dashboard plan generated by agent");
      reporter.setDashboardPlan(parsed);
      reporter.phaseComplete("dashboard-agent", "complete");

      return parsed;
    }

    reporter.decision(
      "dashboard-agent",
      "Fallback",
      "Agent response could not be parsed; using deterministic planner",
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "Dashboard agent failed";
    reporter.log("dashboard-agent", message, "warn");
    reporter.decision(
      "dashboard-agent",
      "Fallback",
      "Agent call failed; using deterministic planner",
    );
  }

  const fallbackPlan = buildDashboardPlanDeterministic(report);
  reporter.setDashboardPlan(fallbackPlan);
  reporter.phaseComplete("dashboard-agent", "complete");

  return fallbackPlan;
};
